[package]
name = "fluxd-pow"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
fluxd-consensus = { path = "../consensus" }
fluxd-primitives = { path = "../primitives" }
equihash = "0.2.2"
blake2b_simd = "1.0"
primitive-types = "0.14"
